# GitHub action to run an encode-decode cycle
name: "Encode-decode"

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Build KIM API and run encoder-decoder
      shell: bash
      run: |
       mkdir build && cd build
       cmake .. -DCMAKE_BUILD_TYPE=Release -DKIM_API_BUILD_EXAMPLES=off
       make -j3
       cp ../examples/simulator-models/Sim_LAMMPS_LJcut_AkersonElliott_Alchemy_PbAu/Alchemy_PbAu.in input.txt
       utils/kim-api-base64-encode -i input.txt output.txt
