# GitHub action to run an encode-decode cycle
name: "Encode-decode"

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm, macos-15-intel, macos-14, macos-15, macos-26]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Homebrew
      if: runner.os == 'macOS'
      run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

    - name: Install dependencies
      if: runner.os == 'macOS'
      run: |
        brew install gcc

    - name: Check compiler installation
      if: runner.os == 'macOS'
      run: |      
        echo "Checking Clang and GCC..."
        which clang++ || echo "Clang++ not found"
        which g++ || echo "G++ not found"
        which gcc || echo "gcc not found"
        which gfortran-14 || echo "gfortran-14 not found"
        clang++ --version || echo "Clang++ version check failed"
        g++ --version || echo "G++ version check failed"
        gfortran-14 --version || echo "gfortran-14 version check failed"

    - name: Build KIM API and run encoder-decoder on Linux
      if: runner.os != 'macOS'
      shell: bash
      run: |
       mkdir build && cd build
       cmake .. -DCMAKE_BUILD_TYPE=Release -DKIM_API_BUILD_EXAMPLES=off
       make -j3
       cp ../examples/simulator-models/Sim_LAMMPS_LJcut_AkersonElliott_Alchemy_PbAu/Alchemy_PbAu.in input.txt
       utils/kim-api-base64-encode -i input.txt output.txt

    - name: Build KIM API and run encoder-decoder on mac
      if: runner.os == 'macOS'
      shell: bash
      run: |
       export CXX17=true
       export CXX=clang++
       export CC=clang
       export FC=gfortran-14
       mkdir build && cd build
       cmake .. -DCMAKE_BUILD_TYPE=Release -DKIM_API_BUILD_EXAMPLES=off
       make -j3
       cp ../examples/simulator-models/Sim_LAMMPS_LJcut_AkersonElliott_Alchemy_PbAu/Alchemy_PbAu.in input.txt
       utils/kim-api-base64-encode -i input.txt output.txt